/* SPDX-License-Identifier: MIT */

/*!
 * \file pr.c
 * \details Implementation of the pr logging functions. The pr functions provide
 * a simple logging mechanism that can be used throughout the program to log
 * messages at different verbosity levels. The pr_verbosity variable controls
 * the verbosity level of the logging, allowing for more or less detailed output
 * based on the needs of the developer. The pr functions can be used to log
 * informational messages, debug messages, warnings, and errors, providing a
 * consistent and flexible way to output log messages throughout the program.
 * The implementation of the pr functions can be designed to write log messages
 * to standard output, standard error, or to a log file, depending on the
 * requirements of the project and the desired logging behaviour.
 */
#include "pr.h"

#include <errno.h>
#include <stdio.h>
#include <string.h>

/*!
 * \brief Global variable that controls the verbosity level of the logging.
 * \details The pr_verbosity variable is an integer that represents the current
 * verbosity level for logging. The logging functions will compare the specified
 * log level of a message against the current verbosity level to determine
 * whether the message should be logged or elided. A lower verbosity level means
 * that only more critical messages (e.g., errors) will be logged, while a
 * higher verbosity level allows for more detailed messages (e.g., debug
 * information) to be logged. By adjusting the value of pr_verbosity, developers
 * can control the amount of log output generated by the program, which can be
 * useful for debugging and monitoring purposes.
 * \note The pr_verbosity variable is initialised to 0, which means that by
 * default, only error messages (pr_level_err) will be logged, while warning,
 * informational, and debug messages will be elided. Developers can increase the
 * verbosity level to include more detailed log messages as needed for debugging
 * or analysis purposes.
 * \note The pr_verbosity variable is a global variable, which means that it can
 * be accessed and modified from anywhere in the program. This allows for
 * flexible control over the logging behaviour, as developers can adjust the
 * verbosity level at runtime based on debugging preferences. However, it also
 * means that care should be taken when modifying pr_verbosity to ensure that it
 * is done in a thread-safe manner if the program is multi-threaded, to avoid
 * potential issues with concurrent access and modification.
 */
int pr_verbosity = 0;

static const char *const level_names[] = {
    [0 ... pr_level_max] = "UNK", [pr_level_err] = "ERR",     [pr_level_warn] = "WARN",
    [pr_level_info] = "INFO",     [pr_level_debug] = "DEBUG", [pr_level_max] = "MAX",
};

static FILE *const *outputs[] = {
    [0 ... pr_level_max] = &stdout,
    [pr_level_err] = &stderr,
    [pr_level_warn] = &stderr,
};

bool pr_logging(enum pr_level level) { return pr_level_err >= level || level <= pr_verbosity; }

int pr_log(enum pr_level level, const char *format, va_list args) {
  /*
   * Elide the log message if the specified level is greater than the current
   * verbosity level, as this allows for more efficient logging by avoiding
   * unnecessary formatting and output operations when the log message would not
   * be displayed due to the verbosity level.
   *
   * Never elide error messages, as they are critical for diagnosing issues and
   * should always be logged regardless of the verbosity level.
   */
  if (pr_level_err < level && level > pr_verbosity) {
    return 0;
  }
  FILE *output = *outputs[level > pr_level_max ? pr_level_max : level];
  if (output == NULL) {
    return 0;
  }
  const int err = errno;
  int rc = vfprintf(output, format, args);
  errno = err;
  return rc;
}

int pr_logf(enum pr_level level, const char *format, ...) {
  va_list args;
  va_start(args, format);
  int rc = pr_log(level, format, args);
  va_end(args);
  return rc;
}

int pr_log_level(enum pr_level level) {
  if (level > pr_level_max) {
    level = pr_level_max;
  }
  return pr_logf(level, "%s: ", level_names[level]);
}

int pr_log_errno(enum pr_level level) { return errno ? pr_logf(level, "%s: ", strerror(errno)) : 0; }

void pr_verbosity_set(int verbosity) { pr_verbosity = verbosity; }

void pr_verbosity_inc(void) {
  if (pr_verbosity < pr_level_max) {
    pr_verbosity++;
  }
}

void pr_verbosity_dec(void) {
  if (pr_verbosity > 0) {
    pr_verbosity--;
  }
}
